apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-with-bc-pipeline
spec:
  params:
    - name: buildconfig-name
      type: string
    - name: namespace
      type: string
    - name: deployment-name
      type: string
  tasks:
    - name: start-oc-build
      params:
        - name: buildconfig
          value: $(params.buildconfig-name)
      taskRef:
        kind: Task
        name: start-oc-build
    - name: restart-deployment-task
      params:
        - name: deployment-name
          value: $(params.deployment-name)
        - name: namespace
          value: $(params.namespace)
      runAfter:
        - start-oc-build
      taskRef:
        kind: Task
        name: restart-deployment
