apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-with-bc-pipeline
spec:
  params:
    - name: buildconfig-name
      type: string
    - name: namespace
      type: string
  tasks:
    - name: start-oc-build
      params:
        - name: buildconfig-name
          value: $(params.buildconfig-name)
        - name: namespace
          value: $(params.namespace)
      taskRef:
        kind: Task
        name: start-oc-build
    - name: apply-manifests
      params:
        - name: manifest-dir
          value: ic-sample-ui/k8s
      runAfter:
        - start-oc-build
      taskRef:
        kind: Task
        name: apply-manifests
  workspaces:
    - name: shared-workspace
