apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ic-sample-ui
  name: ic-sample-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-sample-ui
  template:
    metadata:
      labels:
        app: ic-sample-ui
    spec:
      containers:
        - image:image-registry.openshift-image-registry.svc:5000/ic-pipelines/ic-sample-ui:latest 
          imagePullPolicy: Always
          name: ic-sample-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: IC_SAMPLE_API_SERVICE_HOST
              value: ic-sample-api
            - name: IC_SAMPLE_API_SERVICE_PORT
              value: "8501"
